2021-01-19 16:55:20,553:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 16:55:20,568:root:DEBUG:Finished Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 16:55:20,574:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 16:55:20,574:root:DEBUG:Finished Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 16:55:20,590:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 16:55:20,590:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 16:55:20,605:root:DEBUG:Finished Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 16:55:20,605:root:DEBUG:Finished Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 16:55:20,625:root:DEBUG:Finished Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 16:55:20,628:root:DEBUG:Finished Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 16:55:20,629:root:INFO:finished program
2021-01-19 16:55:20,630:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: loadavg (main)
2021-01-19 16:55:20,632:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: run_cmd (loadavg)
2021-01-19 16:55:20,652:root:CRITICAL:Exception while Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: run_cmd (loadavg)
2021-01-19 16:55:20,652:root:CRITICAL:/proc/loadavg not found, are you using a supported OS?
2021-01-19 16:55:20,654:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: colored (main)
2021-01-19 16:55:20,654:root:DEBUG:Finished Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: colored (main)
2021-01-19 16:55:20,657:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: allocation (main)
2021-01-19 16:55:20,657:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: run_cmd (allocation)
2021-01-19 16:55:20,667:root:CRITICAL:Exception while Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: run_cmd (allocation)
2021-01-19 16:55:20,679:root:CRITICAL:Exception while Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: allocation (main)
2021-01-19 16:55:20,679:root:CRITICAL:command 'free -bt' didn't work, are you using a supported OS?
2021-01-19 16:55:20,681:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: colored (main)
2021-01-19 16:55:20,683:root:DEBUG:Finished Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: colored (main)
2021-01-19 16:56:12,433:root:DEBUG:Importing/using /mnt/c/Users/woelfel/Desktop/Message-of-the-Python/motp/baselib/base.py: <module> (_call_with_frames_removed)
2021-01-19 16:56:12,440:root:DEBUG:Finished Importing/using /mnt/c/Users/woelfel/Desktop/Message-of-the-Python/motp/baselib/base.py: <module> (_call_with_frames_removed)
2021-01-19 16:56:12,450:root:DEBUG:Importing/using /mnt/c/Users/woelfel/Desktop/Message-of-the-Python/motp/baselib/base.py: <module> (_call_with_frames_removed)
2021-01-19 16:56:12,458:root:DEBUG:Finished Importing/using /mnt/c/Users/woelfel/Desktop/Message-of-the-Python/motp/baselib/base.py: <module> (_call_with_frames_removed)
2021-01-19 16:56:12,462:root:DEBUG:Importing/using /mnt/c/Users/woelfel/Desktop/Message-of-the-Python/motp/baselib/base.py: <module> (_call_with_frames_removed)
2021-01-19 16:56:12,471:root:DEBUG:Importing/using /mnt/c/Users/woelfel/Desktop/Message-of-the-Python/motp/baselib/base.py: <module> (_call_with_frames_removed)
2021-01-19 16:56:12,478:root:DEBUG:Finished Importing/using /mnt/c/Users/woelfel/Desktop/Message-of-the-Python/motp/baselib/base.py: <module> (_call_with_frames_removed)
2021-01-19 16:56:12,487:root:DEBUG:Finished Importing/using /mnt/c/Users/woelfel/Desktop/Message-of-the-Python/motp/baselib/base.py: <module> (_call_with_frames_removed)
2021-01-19 16:56:12,495:root:DEBUG:Finished Importing/using /mnt/c/Users/woelfel/Desktop/Message-of-the-Python/motp/baselib/base.py: <module> (_call_with_frames_removed)
2021-01-19 16:56:12,499:root:DEBUG:Finished Importing/using /mnt/c/Users/woelfel/Desktop/Message-of-the-Python/motp/baselib/base.py: <module> (_call_with_frames_removed)
2021-01-19 16:56:12,499:root:INFO:finished program
2021-01-19 16:56:12,501:root:DEBUG:Importing/using /mnt/c/Users/woelfel/Desktop/Message-of-the-Python/motp/baselib/base.py: loadavg (main)
2021-01-19 16:56:12,503:root:DEBUG:Importing/using /mnt/c/Users/woelfel/Desktop/Message-of-the-Python/motp/baselib/base.py: run_cmd (loadavg)
2021-01-19 16:56:12,516:root:DEBUG:Finished Importing/using /mnt/c/Users/woelfel/Desktop/Message-of-the-Python/motp/baselib/base.py: run_cmd (loadavg)
2021-01-19 16:56:12,517:root:DEBUG:Finished Importing/using /mnt/c/Users/woelfel/Desktop/Message-of-the-Python/motp/baselib/base.py: loadavg (main)
2021-01-19 16:56:12,519:root:DEBUG:Importing/using /mnt/c/Users/woelfel/Desktop/Message-of-the-Python/motp/baselib/base.py: colored (main)
2021-01-19 16:56:12,521:root:DEBUG:Finished Importing/using /mnt/c/Users/woelfel/Desktop/Message-of-the-Python/motp/baselib/base.py: colored (main)
2021-01-19 16:56:12,523:root:DEBUG:Importing/using /mnt/c/Users/woelfel/Desktop/Message-of-the-Python/motp/baselib/base.py: allocation (main)
2021-01-19 16:56:12,526:root:DEBUG:Importing/using /mnt/c/Users/woelfel/Desktop/Message-of-the-Python/motp/baselib/base.py: run_cmd (allocation)
2021-01-19 16:56:12,539:root:DEBUG:Finished Importing/using /mnt/c/Users/woelfel/Desktop/Message-of-the-Python/motp/baselib/base.py: run_cmd (allocation)
2021-01-19 16:56:12,541:root:DEBUG:Finished Importing/using /mnt/c/Users/woelfel/Desktop/Message-of-the-Python/motp/baselib/base.py: allocation (main)
2021-01-19 16:56:12,543:root:DEBUG:Importing/using /mnt/c/Users/woelfel/Desktop/Message-of-the-Python/motp/baselib/base.py: colored (main)
2021-01-19 16:56:12,545:root:DEBUG:Finished Importing/using /mnt/c/Users/woelfel/Desktop/Message-of-the-Python/motp/baselib/base.py: colored (main)
2021-01-19 17:01:27,155:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 17:01:27,162:root:DEBUG:Finished Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 17:01:27,171:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 17:01:27,179:root:DEBUG:Finished Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 17:01:27,183:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 17:01:27,193:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 17:01:27,200:root:DEBUG:Finished Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 17:01:27,209:root:DEBUG:Finished Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 17:01:27,217:root:DEBUG:Finished Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 17:01:27,221:root:DEBUG:Finished Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 17:01:27,221:root:INFO:finished program
2021-01-19 17:01:27,223:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: loadavg (main)
2021-01-19 17:01:27,225:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: run_cmd (loadavg)
2021-01-19 17:01:27,242:root:CRITICAL:Exception while Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: run_cmd (loadavg)
2021-01-19 17:01:27,242:root:CRITICAL:/proc/loadavg not found, are you using a supported OS?
2021-01-19 17:01:27,244:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: colored (main)
2021-01-19 17:01:27,246:root:DEBUG:Finished Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: colored (main)
2021-01-19 17:01:27,256:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: allocation (main)
2021-01-19 17:01:27,258:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: run_cmd (allocation)
2021-01-19 17:01:27,268:root:CRITICAL:Exception while Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: run_cmd (allocation)
2021-01-19 17:01:27,278:root:CRITICAL:Exception while Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: allocation (main)
2021-01-19 17:01:27,278:root:CRITICAL:command 'free -bt' didn't work, are you using a supported OS?
2021-01-19 17:01:27,280:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: colored (main)
2021-01-19 17:01:27,282:root:DEBUG:Finished Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: colored (main)
2021-01-19 17:02:21,115:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 17:02:21,119:root:DEBUG:Finished Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 17:02:21,131:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 17:02:21,131:root:DEBUG:Finished Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 17:02:21,131:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 17:02:21,147:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 17:02:21,147:root:DEBUG:Finished Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 17:02:21,162:root:DEBUG:Finished Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 17:02:21,162:root:DEBUG:Finished Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 17:02:21,178:root:DEBUG:Finished Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 17:02:21,178:root:INFO:finished program
2021-01-19 17:02:21,178:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: loadavg (main)
2021-01-19 17:02:21,178:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: run_cmd (loadavg)
2021-01-19 17:02:21,193:root:CRITICAL:Exception while Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: run_cmd (loadavg)
2021-01-19 17:02:21,200:root:CRITICAL:/proc/loadavg not found, are you using a supported OS?
2021-01-19 17:02:21,202:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: colored (main)
2021-01-19 17:02:21,204:root:DEBUG:Finished Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: colored (main)
2021-01-19 17:02:21,213:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: allocation (main)
2021-01-19 17:02:21,215:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: run_cmd (allocation)
2021-01-19 17:02:21,225:root:CRITICAL:Exception while Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: run_cmd (allocation)
2021-01-19 17:02:21,231:root:CRITICAL:Exception while Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: allocation (main)
2021-01-19 17:02:21,232:root:CRITICAL:command 'free -bt' didn't work, are you using a supported OS?
2021-01-19 17:02:21,234:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: colored (main)
2021-01-19 17:02:21,235:root:DEBUG:Finished Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: colored (main)
2021-01-19 17:02:28,884:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 17:02:28,900:root:DEBUG:Finished Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 17:02:28,900:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 17:02:28,915:root:DEBUG:Finished Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 17:02:28,915:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 17:02:28,931:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 17:02:28,931:root:DEBUG:Finished Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 17:02:28,947:root:DEBUG:Finished Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 17:02:28,953:root:DEBUG:Finished Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 17:02:28,953:root:DEBUG:Finished Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 17:02:28,953:root:INFO:finished program
2021-01-19 17:02:28,953:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: loadavg (main)
2021-01-19 17:02:28,953:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: run_cmd (loadavg)
2021-01-19 17:02:28,969:root:CRITICAL:Exception while Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: run_cmd (loadavg)
2021-01-19 17:02:28,981:root:CRITICAL:/proc/loadavg not found, are you using a supported OS?
2021-01-19 17:02:28,983:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: colored (main)
2021-01-19 17:02:28,985:root:DEBUG:Finished Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: colored (main)
2021-01-19 17:02:28,994:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: allocation (main)
2021-01-19 17:02:28,996:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: run_cmd (allocation)
2021-01-19 17:02:29,006:root:CRITICAL:Exception while Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: run_cmd (allocation)
2021-01-19 17:02:29,009:root:CRITICAL:Exception while Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: allocation (main)
2021-01-19 17:02:29,009:root:CRITICAL:command 'free -bt' didn't work, are you using a supported OS?
2021-01-19 17:02:29,011:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: colored (main)
2021-01-19 17:02:29,013:root:DEBUG:Finished Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: colored (main)
2021-01-19 17:03:17,442:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 17:03:17,442:root:DEBUG:Finished Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 17:03:17,458:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 17:03:17,458:root:DEBUG:Finished Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 17:03:17,458:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 17:03:17,473:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 17:03:17,489:root:DEBUG:Finished Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 17:03:17,489:root:DEBUG:Finished Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 17:03:17,504:root:DEBUG:Finished Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 17:03:17,504:root:DEBUG:Finished Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 17:03:17,504:root:INFO:finished program
2021-01-19 17:03:17,504:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: loadavg (main)
2021-01-19 17:03:17,504:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: run_cmd (loadavg)
2021-01-19 17:03:17,520:root:CRITICAL:Exception while Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: run_cmd (loadavg)
2021-01-19 17:03:17,531:root:CRITICAL:/proc/loadavg not found, are you using a supported OS?
2021-01-19 17:03:17,533:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: colored (main)
2021-01-19 17:03:17,535:root:DEBUG:Finished Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: colored (main)
2021-01-19 17:03:17,545:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: allocation (main)
2021-01-19 17:03:17,547:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: run_cmd (allocation)
2021-01-19 17:03:17,556:root:CRITICAL:Exception while Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: run_cmd (allocation)
2021-01-19 17:03:17,558:root:CRITICAL:Exception while Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: allocation (main)
2021-01-19 17:03:17,558:root:CRITICAL:command 'free -bt' didn't work, are you using a supported OS?
2021-01-19 17:03:17,560:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: colored (main)
2021-01-19 17:03:17,562:root:DEBUG:Finished Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: colored (main)
2021-01-19 17:03:45,788:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 17:03:45,788:root:DEBUG:Finished Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 17:03:45,804:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 17:03:45,804:root:DEBUG:Finished Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 17:03:45,804:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 17:03:45,819:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 17:03:45,819:root:DEBUG:Finished Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 17:03:45,835:root:DEBUG:Finished Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 17:03:45,851:root:DEBUG:Finished Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 17:03:45,851:root:DEBUG:Finished Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 17:03:45,851:root:INFO:finished program
2021-01-19 17:03:45,851:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: loadavg (main)
2021-01-19 17:03:45,851:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: run_cmd (loadavg)
2021-01-19 17:03:45,866:root:CRITICAL:Exception while Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: run_cmd (loadavg)
2021-01-19 17:03:45,866:root:CRITICAL:/proc/loadavg not found, are you using a supported OS?
2021-01-19 17:03:45,866:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: colored (main)
2021-01-19 17:03:45,866:root:DEBUG:Finished Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: colored (main)
2021-01-19 17:03:45,866:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: allocation (main)
2021-01-19 17:03:45,882:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: run_cmd (allocation)
2021-01-19 17:03:45,888:root:CRITICAL:Exception while Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: run_cmd (allocation)
2021-01-19 17:03:45,888:root:CRITICAL:Exception while Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: allocation (main)
2021-01-19 17:03:45,888:root:CRITICAL:command 'free -bt' didn't work, are you using a supported OS?
2021-01-19 17:03:45,888:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: colored (main)
2021-01-19 17:03:45,888:root:DEBUG:Finished Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: colored (main)
2021-01-19 17:04:34,349:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 17:04:34,349:root:DEBUG:Finished Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 17:04:34,364:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 17:04:34,380:root:DEBUG:Finished Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 17:04:34,380:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 17:04:34,387:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 17:04:34,387:root:DEBUG:Finished Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 17:04:34,402:root:DEBUG:Finished Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 17:04:34,402:root:DEBUG:Finished Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 17:04:34,418:root:DEBUG:Finished Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 17:04:34,418:root:INFO:finished program
2021-01-19 17:04:34,418:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: loadavg (main)
2021-01-19 17:04:34,418:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: run_cmd (loadavg)
2021-01-19 17:04:34,433:root:CRITICAL:Exception while Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: run_cmd (loadavg)
2021-01-19 17:04:34,433:root:CRITICAL:/proc/loadavg not found, are you using a supported OS?
2021-01-19 17:04:34,433:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: colored (main)
2021-01-19 17:04:34,433:root:DEBUG:Finished Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: colored (main)
2021-01-19 17:04:34,433:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: allocation (main)
2021-01-19 17:04:34,449:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: run_cmd (allocation)
2021-01-19 17:04:34,449:root:CRITICAL:Exception while Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: run_cmd (allocation)
2021-01-19 17:04:34,449:root:CRITICAL:Exception while Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: allocation (main)
2021-01-19 17:04:34,449:root:CRITICAL:command 'free -bt' didn't work, are you using a supported OS?
2021-01-19 17:04:34,449:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: colored (main)
2021-01-19 17:04:34,449:root:DEBUG:Finished Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: colored (main)
2021-01-19 17:04:43,738:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 17:04:43,746:root:DEBUG:Finished Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 17:04:43,755:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 17:04:43,764:root:DEBUG:Finished Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 17:04:43,768:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 17:04:43,777:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 17:04:43,786:root:DEBUG:Finished Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 17:04:43,795:root:DEBUG:Finished Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 17:04:43,802:root:DEBUG:Finished Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 17:04:43,802:root:DEBUG:Finished Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 17:04:43,802:root:INFO:finished program
2021-01-19 17:04:43,802:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: loadavg (main)
2021-01-19 17:04:43,802:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: run_cmd (loadavg)
2021-01-19 17:04:43,816:root:CRITICAL:Exception while Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: run_cmd (loadavg)
2021-01-19 17:04:43,816:root:CRITICAL:/proc/loadavg not found, are you using a supported OS?
2021-01-19 17:04:43,830:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: colored (main)
2021-01-19 17:04:43,831:root:DEBUG:Finished Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: colored (main)
2021-01-19 17:04:43,833:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: allocation (main)
2021-01-19 17:04:43,835:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: run_cmd (allocation)
2021-01-19 17:04:43,845:root:CRITICAL:Exception while Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: run_cmd (allocation)
2021-01-19 17:04:43,847:root:CRITICAL:Exception while Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: allocation (main)
2021-01-19 17:04:43,851:root:CRITICAL:command 'free -bt' didn't work, are you using a supported OS?
2021-01-19 17:04:43,853:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: colored (main)
2021-01-19 17:04:43,855:root:DEBUG:Finished Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: colored (main)
2021-01-19 17:04:46,752:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 17:04:46,759:root:DEBUG:Finished Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 17:04:46,769:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 17:04:46,777:root:DEBUG:Finished Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 17:04:46,781:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 17:04:46,790:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 17:04:46,798:root:DEBUG:Finished Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 17:04:46,805:root:DEBUG:Finished Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 17:04:46,814:root:DEBUG:Finished Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 17:04:46,817:root:DEBUG:Finished Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 17:04:46,817:root:INFO:finished program
2021-01-19 17:04:46,817:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: loadavg (main)
2021-01-19 17:04:46,817:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: run_cmd (loadavg)
2021-01-19 17:04:46,827:root:CRITICAL:Exception while Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: run_cmd (loadavg)
2021-01-19 17:04:46,838:root:CRITICAL:/proc/loadavg not found, are you using a supported OS?
2021-01-19 17:04:46,839:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: colored (main)
2021-01-19 17:04:46,841:root:DEBUG:Finished Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: colored (main)
2021-01-19 17:04:46,850:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: allocation (main)
2021-01-19 17:04:46,850:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: run_cmd (allocation)
2021-01-19 17:04:46,850:root:CRITICAL:Exception while Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: run_cmd (allocation)
2021-01-19 17:04:46,863:root:CRITICAL:Exception while Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: allocation (main)
2021-01-19 17:04:46,863:root:CRITICAL:command 'free -bt' didn't work, are you using a supported OS?
2021-01-19 17:04:46,865:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: colored (main)
2021-01-19 17:04:46,867:root:DEBUG:Finished Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: colored (main)
2021-01-19 17:05:42,496:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 17:05:42,496:root:DEBUG:Finished Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 17:05:42,512:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 17:05:42,512:root:DEBUG:Finished Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 17:05:42,512:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 17:05:42,527:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 17:05:42,527:root:DEBUG:Finished Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 17:05:42,543:root:DEBUG:Finished Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 17:05:42,543:root:DEBUG:Finished Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 17:05:42,558:root:DEBUG:Finished Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: <module> (_call_with_frames_removed)
2021-01-19 17:05:42,558:root:INFO:finished program
2021-01-19 17:05:42,558:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: loadavg (main)
2021-01-19 17:05:42,558:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: run_cmd (loadavg)
2021-01-19 17:05:42,581:root:CRITICAL:Exception while Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: run_cmd (loadavg)
2021-01-19 17:05:42,582:root:CRITICAL:/proc/loadavg not found, are you using a supported OS?
2021-01-19 17:05:42,584:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: colored (main)
2021-01-19 17:05:42,585:root:DEBUG:Finished Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: colored (main)
2021-01-19 17:05:42,597:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: allocation (main)
2021-01-19 17:05:42,599:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: run_cmd (allocation)
2021-01-19 17:05:42,610:root:CRITICAL:Exception while Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: run_cmd (allocation)
2021-01-19 17:05:42,611:root:CRITICAL:Exception while Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: allocation (main)
2021-01-19 17:05:42,612:root:CRITICAL:command 'free -bt' didn't work, are you using a supported OS?
2021-01-19 17:05:42,614:root:DEBUG:Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: colored (main)
2021-01-19 17:05:42,615:root:DEBUG:Finished Importing/using C:\Users\woelfel\Desktop\Message-of-the-Python\motp\baselib\base.py: colored (main)
